### ISSUE TITLE
AttributeError: 'Florence2LanguageConfig' object has no attribute 'forced_bos_token_id'

### ISSUE THREAD

**Issue by daproject85** [kijai/ComfyUI-Florence2#199]
i cannot get this node to work. I have transformer version 5, and cannot revert back to an older version. What is the solution here?

**Comment by kijai** [comment]
You probably just don't have the latest version, it works with transformers 5.3 at least.

**Comment by daproject85** [comment]
How do I get transformer 5.3. The highest pop installs is 5.0

**Comment by Deaquay** [comment]
I have transformers 5.7.0, and I get the same problem.

**Comment by kijai** [comment]
With the latest version, transformers is not used at all.

**Comment by Deaquay** [comment]
fantastic, gonna try it out asap
